# Check for user setup in keystone 

# Get Glance Keystone variables 
# admin_user:        openstack-config --get /etc/glance/glance-api.conf keystone_authtoken admin_user
# admin_password:    openstack-config --get /etc/glance/glance-api.conf keystone_authtoken admin_password
# admin_tenant_name: openstack-config --get /etc/glance/glance-api.conf keystone_authtoken admin_tenant_name
# auth_uri:          openstack-config --get /etc/glance/glance-api.conf keystone_authtoken auth_uri
# identity_uri:      openstack-config --get /etc/glance/glance-api.conf keystone_authtoken identity_uri
# admin_user:        openstack-config --get /etc/glance/glance-registry.conf keystone_authtoken admin_user
# admin_password:    openstack-config --get /etc/glance/glance-registry.conf keystone_authtoken admin_password
# admin_tenant_name: openstack-config --get /etc/glance/glance-registry.conf keystone_authtoken admin_tenant_name
# auth_uri:          openstack-config --get /etc/glance/glance-registry.conf keystone_authtoken auth_uri
# identity_uri:      openstack-config --get /etc/glance/glance-registry.conf keystone_authtoken identity_uri


- name: Get Glance API Keystone admin User
  shell: openstack-config --get /etc/glance/glance-api.conf keystone_authtoken admin_user
  register: glance_api_keystone_admin_user
  changed_when: no
  ignore_errors: yes

- name: Get Glance API Keystone admin Password
  shell: openstack-config --get /etc/glance/glance-api.conf keystone_authtoken admin_password
  register: glance_api_keystone_admin_password
  changed_when: no
  ignore_errors: yes

- name: Get Glance API Keystone admin Tenant
  shell: openstack-config --get /etc/glance/glance-api.conf keystone_authtoken admin_tenant_name
  register: glance_api_keystone_admin_tenant_name
  changed_when: no
  ignore_errors: yes

- name: Get Glance API Keystone auth_uri
  shell: openstack-config --get /etc/glance/glance-api.conf keystone_authtoken auth_uri
  register: glance_api_keystone_auth_uri
  changed_when: no
  ignore_errors: yes

- name: Get Glance API Keystone identity_uri
  shell: openstack-config --get /etc/glance/glance-api.conf keystone_authtoken identity_uri
  register: glance_api_keystone_identity_uri
  changed_when: no
  ignore_errors: yes

- name: Get Glance Registry Keystone admin User
  shell: openstack-config --get /etc/glance/glance-registry.conf keystone_authtoken admin_user
  register: glance_registry_keystone_admin_user
  changed_when: no
  ignore_errors: yes

- name: Get Glance Registry Keystone admin Password
  shell: openstack-config --get /etc/glance/glance-registry.conf keystone_authtoken admin_password
  register: glance_registry_keystone_admin_password
  changed_when: no
  ignore_errors: yes

- name: Get Glance Registry Keystone admin Tenant
  shell: openstack-config --get /etc/glance/glance-registry.conf keystone_authtoken admin_tenant_name
  register: glance_registry_keystone_admin_tenant_name
  changed_when: no
  ignore_errors: yes

- name: Get Glance Registry Keystone auth_uri
  shell: openstack-config --get /etc/glance/glance-registry.conf keystone_authtoken auth_uri
  register: glance_registry_keystone_auth_uri
  changed_when: no
  ignore_errors: yes

- name: Get Glance Registry Keystone identity_uri
  shell: openstack-config --get /etc/glance/glance-registry.conf keystone_authtoken identity_uri
  register: glance_registry_keystone_identity_uri
  changed_when: no
  ignore_errors: yes

- name: Check glance-api keystone token get 
  shell: export OS_USERNAME={{glance_api_keystone_admin_user.stdout}};export OS_PASSWORD={{glance_api_keystone_admin_password.stdout}};export OS_TENANT_NAME={{glance_api_keystone_admin_tenant_name.stdout}}; export OS_AUTH_URL={{glance_api_keystone_auth_uri.stdout}}; keystone token-get
  register: glance_api_keystone_token_get
  changed_when: no
  ignore_errors: yes

- name: Check glance-registry keystone token get
  shell: export OS_USERNAME={{glance_registry_keystone_admin_user.stdout}};export OS_PASSWORD={{glance_registry_keystone_admin_password.stdout}};export OS_TENANT_NAME={{glance_registry_keystone_admin_tenant_name.stdout}}; export OS_AUTH_URL={{glance_registry_keystone_auth_uri.stdout}}; keystone token-get
  register: glance_registry_keystone_token_get
  changed_when: no
  ignore_errors: yes

- name: Get Glance keystone endpoint 
  shell: export OS_USERNAME={{glance_registry_keystone_admin_user.stdout}};export OS_PASSWORD={{glance_registry_keystone_admin_password.stdout}};export OS_TENANT_NAME={{glance_registry_keystone_admin_tenant_name.stdout}}; export OS_AUTH_URL={{glance_registry_keystone_auth_uri.stdout}}; keystone endpoint-get --service image | grep public | awk '{print $4}'
  register: glance_keystone_endpoint
  failed_when: "{{ glance_keystone_endpoint.rc }} != 0"
  changed_when: no
  ignore_errors: yes

- name: Check Glance keystone endpoint 
  shell: curl -k {{ glance_keystone_endpoint.stdout }}
  register: glance_keystone_endpoint_response
  failed_when: "{{ glance_keystone_endpoint_response.rc  }} != 0"
  changed_when: no
  ignore_errors: yes


